stages:
  - build
  - test

.base-build:
  stage: build
  timeout: 12h
  needs:
    pipeline: $PARENT_PIPELINE_ID
    job: pipeline-configure
  variables:
    SLURM_TIMELIMIT: 180
  script:
  - ./uenv-pipeline/stage-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/uenv-build -m $STACK_MOUNT -u $STACK_UARCH $NO_BWRAP
  after_script:
  - rm -Rf /dev/shm/uenv-build

.base-test:
  stage: test
  timeout: 8h
  needs:
    pipeline: $PARENT_PIPELINE_ID
    job: pipeline-configure
  variables:
    SLURM_TIMELIMIT: 180
  script:
  - ./uenv-pipeline/stage-test -n $STACK_NAME -s $STACK_SYSTEM -m $STACK_MOUNT -u $STACK_UARCH

{% for job in jobs %}

build-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}:
  extends: .base-build
{% if job.runner.f7t %}
  tags: ["f7t-runner"]
{% else %}
  tags: ["{{job.runner.slurm_runner}}"]
{% endif %}
  variables:
    STACK_MOUNT:      "{{job.mount}}"
    NO_BWRAP:         "{{job.no_bwrap}}"
    STACK_NAME:       "{{job.uenv}}/{{job.version}}"
    STACK_SYSTEM:     "{{job.system}}"
    STACK_RECIPE:     "{{job.recipe_path}}"
    STACK_UARCH:      "{{job.uarch}}"
    SLURM_PARTITION:  "{{job.partition}}"
    {% for name, value in job.runner.variables.items() %}
    {{ name }}: "{{ value }}"
    {% endfor %}

test-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}:
  extends: .base-test
{% if job.runner.f7t %}
  tags: ["f7t-runner"]
{% else %}
  tags: ["{{job.runner.slurm_runner}}"]
{% endif %}
  needs:
    # Repeat the needs for the parent pipeline. Only specifying the build-* job
    # as a needs here would override the needs for the parent pipeline. Not
    # depending on the parent pipeline means that the artifact from the parent
    # pipeline isn't downloaded, which contains e.g. the checkout of
    # uenv-pipeline.
    - pipeline: $PARENT_PIPELINE_ID
      job: pipeline-configure
    - job: "build-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}"
  variables:
    STACK_NAME:       "{{job.uenv}}/{{job.version}}"
    STACK_SYSTEM:     "{{job.system}}"
    STACK_UARCH:      "{{job.uarch}}"
    STACK_MOUNT:      "{{job.mount}}"
    SLURM_PARTITION:  "{{job.partition}}"
    {% for name, value in job.runner.variables.items() %}
    {{ name }}: "{{ value }}"
    {% endfor %}
  artifacts:
    when: always
    paths:
      - "*/cscs-reframe-tests/reframe.out"
      - "*/cscs-reframe-tests/reframe.log"

{% endfor %}



{% for job in jobs %}
#@@cmd@@STACK_NAME="{{job.uenv}}/{{job.version}}"
#@@cmd@@STACK_SYSTEM="{{job.system}}"
#@@cmd@@STACK_RECIPE="{{job.recipe_path}}"
#@@cmd@@STACK_MOUNT="{{job.mount}}"
#@@cmd@@STACK_UARCH="{{job.uarch}}"
#@@cmd@@NO_BWRAP="{{job.no_bwrap}}"
#@@cmd@@./uenv-pipeline/stage-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/uenv-build -m $STACK_MOUNT -u $STACK_UARCH $NO_BWRAP ${TESTRUN}
{% endfor %}
